### ISSUE TITLE
unicode error when resolving conflicts with text edition

### ISSUE THREAD

**Issue by tonthon** [mike-perdide/gitbuster#10]
When using Adding the file with a custom content, if you put some non-ascii character in the 'Unmerged state' text dialog, the following error raises into the prompt : 

Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/gitbuster-0.9b4-py2.7.egg/gitbuster/conflicts_dialog.py", line 121, in item_clicked
    self.set_choice()
  File "/usr/local/lib/python2.7/dist-packages/gitbuster-0.9b4-py2.7.egg/gitbuster/conflicts_dialog.py", line 105, in set_choice
    custom_content = str(self._ui.conflictTextEdit.toPlainText())
UnicodeEncodeError: 'ascii' codec can't encode character u'\xe9' in position 9: ordinal not in range(128)

**Comment by mike-perdide** [comment]
This is fixed by : https://github.com/mike-perdide/gitbuster/commit/9abe008c8ce2ac9a172a1696125c1984d0bad0b8.
